# 🛠 Exercises

In [3]:
import tensorflow as tf

scalar = tf.constant(3)
vector = tf.constant([10,7])
matrix = tf.constant([[3,7],[5,8]])

scalar, vector, matrix

(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 7],
        [5, 8]], dtype=int32)>)

In [13]:
tf.shape(scalar).numpy(), tf.rank(scalar).numpy(),tf.size(scalar).numpy()

(array([], dtype=int32), 0, 1)

In [14]:
tf.shape(vector).numpy(), tf.rank(vector).numpy(),tf.size(vector).numpy()

(array([2], dtype=int32), 1, 2)

In [15]:
tf.shape(matrix).numpy(), tf.rank(matrix).numpy(),tf.size(matrix).numpy()

(array([2, 2], dtype=int32), 2, 4)

In [18]:
A = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)
B = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)

A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.12390947, 0.5307603 , 0.0367285 , ..., 0.4082111 , 0.394413  ,
        0.20036209],
       [0.539798  , 0.7605978 , 0.9670681 , ..., 0.7102636 , 0.21620286,
        0.6561873 ],
       [0.6120064 , 0.7608795 , 0.02416432, ..., 0.71754825, 0.5684476 ,
        0.45940912],
       [0.16957402, 0.94188297, 0.5865966 , ..., 0.32317436, 0.44076097,
        0.259053  ],
       [0.30204237, 0.22864926, 0.72114897, ..., 0.58788204, 0.42046213,
        0.1279335 ]], dtype=float32)>

In [22]:
tf.matmul(A, tf.reshape(B,shape=(300,5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.88577 , 69.71536 , 68.952126, 71.82693 , 73.67316 ],
       [73.48217 , 72.35834 , 73.23366 , 72.355354, 74.68624 ],
       [75.19649 , 71.0621  , 71.236786, 75.00189 , 76.661095],
       [76.79691 , 73.84659 , 74.695786, 78.067535, 77.70268 ],
       [75.72052 , 73.895424, 75.61371 , 76.06999 , 73.89123 ]],
      dtype=float32)>

In [23]:
tf.multiply(A,B)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[6.91851601e-04, 8.41566101e-02, 2.59778611e-02, ...,
        3.16878587e-01, 1.74065605e-02, 1.13641515e-01],
       [3.31524760e-01, 6.31680965e-01, 2.12850228e-01, ...,
        2.00587004e-01, 2.08858490e-01, 3.23331624e-01],
       [3.95091981e-01, 1.28925994e-01, 3.79046402e-03, ...,
        4.28866535e-01, 1.75844654e-01, 2.25041300e-01],
       [6.72801286e-02, 8.20730567e-01, 4.00431484e-01, ...,
        3.38528715e-02, 1.58064991e-01, 3.08539458e-02],
       [2.88608789e-01, 1.88504495e-02, 3.27376783e-01, ...,
        3.32682014e-01, 6.16051182e-02, 5.66223487e-02]], dtype=float32)>

In [25]:
C = tf.random.uniform(shape=(244,244,3),minval=0,maxval=1)
C

<tf.Tensor: shape=(244, 244, 3), dtype=float32, numpy=
array([[[0.75967574, 0.8971659 , 0.7664248 ],
        [0.3147142 , 0.3281629 , 0.16159844],
        [0.72007227, 0.12888026, 0.87043417],
        ...,
        [0.71442115, 0.5358821 , 0.5639274 ],
        [0.1142168 , 0.05417979, 0.31612992],
        [0.9852053 , 0.536499  , 0.97870016]],

       [[0.2686926 , 0.4818747 , 0.2467345 ],
        [0.92631567, 0.3607453 , 0.6993201 ],
        [0.9402003 , 0.9757017 , 0.8807689 ],
        ...,
        [0.07710493, 0.54006374, 0.6176913 ],
        [0.54691136, 0.06854546, 0.33102477],
        [0.476272  , 0.8558936 , 0.53076756]],

       [[0.3547206 , 0.9918977 , 0.6154301 ],
        [0.8449985 , 0.738749  , 0.88668835],
        [0.68082297, 0.4043461 , 0.65758765],
        ...,
        [0.46475434, 0.55061114, 0.8906232 ],
        [0.39185858, 0.18317163, 0.56749344],
        [0.82112956, 0.9311205 , 0.26033497]],

       ...,

       [[0.670467  , 0.27269447, 0.93324125],
        [0.67

In [29]:
tf.reduce_min(C).numpy()

3.9339066e-06

In [30]:
tf.reduce_max(C).numpy()

0.9999759

In [31]:
D = tf.random.uniform(shape=(1,244,244,3),minval=0,maxval=1)
D

<tf.Tensor: shape=(1, 244, 244, 3), dtype=float32, numpy=
array([[[[0.95683134, 0.16213465, 0.8862431 ],
         [0.17297947, 0.9751017 , 0.7780477 ],
         [0.43602085, 0.07380152, 0.09792638],
         ...,
         [0.7656125 , 0.27975643, 0.8695469 ],
         [0.27060318, 0.8882742 , 0.09115243],
         [0.4721949 , 0.13312423, 0.4764316 ]],

        [[0.37938118, 0.56791425, 0.15883005],
         [0.13017738, 0.7807622 , 0.551703  ],
         [0.92209744, 0.545156  , 0.60472226],
         ...,
         [0.6678307 , 0.3850987 , 0.41366768],
         [0.55840266, 0.1509502 , 0.85788965],
         [0.9201591 , 0.69396806, 0.09894025]],

        [[0.10742605, 0.31090486, 0.09701478],
         [0.13032663, 0.7211304 , 0.40520692],
         [0.6186193 , 0.45486295, 0.69304204],
         ...,
         [0.1293639 , 0.9907198 , 0.43680632],
         [0.12319517, 0.5597187 , 0.27652884],
         [0.7816584 , 0.97770286, 0.9903791 ]],

        ...,

        [[0.74041855, 0.23813474, 

In [32]:
tf.squeeze(D)

<tf.Tensor: shape=(244, 244, 3), dtype=float32, numpy=
array([[[0.95683134, 0.16213465, 0.8862431 ],
        [0.17297947, 0.9751017 , 0.7780477 ],
        [0.43602085, 0.07380152, 0.09792638],
        ...,
        [0.7656125 , 0.27975643, 0.8695469 ],
        [0.27060318, 0.8882742 , 0.09115243],
        [0.4721949 , 0.13312423, 0.4764316 ]],

       [[0.37938118, 0.56791425, 0.15883005],
        [0.13017738, 0.7807622 , 0.551703  ],
        [0.92209744, 0.545156  , 0.60472226],
        ...,
        [0.6678307 , 0.3850987 , 0.41366768],
        [0.55840266, 0.1509502 , 0.85788965],
        [0.9201591 , 0.69396806, 0.09894025]],

       [[0.10742605, 0.31090486, 0.09701478],
        [0.13032663, 0.7211304 , 0.40520692],
        [0.6186193 , 0.45486295, 0.69304204],
        ...,
        [0.1293639 , 0.9907198 , 0.43680632],
        [0.12319517, 0.5597187 , 0.27652884],
        [0.7816584 , 0.97770286, 0.9903791 ]],

       ...,

       [[0.74041855, 0.23813474, 0.17095923],
        [0.64

In [42]:
E = tf.constant([5,6,1,2,8,9,3,4,6,0])

print("The position of max value is:", tf.argmax(E).numpy())
print("The of max value is:", E[tf.argmax(E).numpy()].numpy())

#hard way to do it



The position of max value is: 5
The of max value is: 9


In [44]:
tf.one_hot(E,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>